import {
  Sparkles,
  Bot,
  Brain,
  Layers,
  Wrench,
  Globe,
  Shield,
  Flag,
} from "lucide-react";
import type { SlideMeta } from "./types";

export const SLIDES: SlideMeta[] = [
  {
    id: "intro",
    index: 1,
    label: "Intro",
    icon: Sparkles,
    section: "SECTION 01",
    title: "Intro",
    nextLabel: "What is an Agent?",
  },
  {
    id: "what-is-agent",
    index: 2,
    label: "Agent là gì?",
    icon: Bot,
    section: "SECTION 02",
    title: "Agent là gì?",
    nextLabel: "Cách Agent suy nghĩ",
  },
  {
    id: "how-agents-think",
    index: 3,
    label: "Suy nghĩ",
    icon: Brain,
    section: "SECTION 03",
    title: "Cách Agent suy nghĩ",
    nextLabel: "Kiến trúc",
  },
  {
    id: "architecture",
    index: 4,
    label: "Kiến trúc",
    icon: Layers,
    section: "SECTION 04",
    title: "Kiến trúc Agent",
    nextLabel: "Công cụ",
  },
  {
    id: "tools",
    index: 5,
    label: "Công cụ",
    icon: Wrench,
    section: "SECTION 05",
    title: "Tools & Actions",
    nextLabel: "Thực tế",
  },
  {
    id: "real-world",
    index: 6,
    label: "Thực tế",
    icon: Globe,
    section: "SECTION 06",
    title: "Agent trong thực tế",
    nextLabel: "Best Practices",
  },
  {
    id: "best-practices",
    index: 7,
    label: "Best Practices",
    icon: Shield,
    section: "SECTION 07",
    title: "Best Practices",
    nextLabel: "Kết thúc",
  },
  {
    id: "outro",
    index: 8,
    label: "Kết thúc",
    icon: Flag,
    section: "SECTION 08",
    title: "Kết thúc",
    nextLabel: "Finish",
  },
];
